name: Deploy to PROD

on:
  release:
    types: [published]
    tags:
      - "v*"
env:
  REACT_APP_WEBSOCKET_SERVER: ${{ secrets.REACT_APP_WEBSOCKET_SERVER_PROD }}
  REACT_APP_PUBLIC_URL: ${{ secrets.PUBLIC_URL_PROD }}
  REACT_APP_VERSE_BASE_URL: ${{ secrets.VERSE_URL_PROD }}
  REACT_APP_AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_KEY_PROD }}
  REACT_APP_GOERLI_NODE_HTTP_URL: ${{ vars.DEV_GOERLI_NODE_HTTP_URL }}
  REACT_APP_GOERLI_NODE_WSS_URL: ${{ vars.DEV_GOERLI_NODE_WSS_URL }}
  REACT_APP_SEPOLIA_NODE_HTTP_URL: ${{ vars.DEV_SEPOLIA_NODE_HTTP_URL }}
  REACT_APP_SEPOLIA_NODE_WSS_URL: ${{ vars.DEV_SEPOLIA_NODE_WSS_URL }}
  REACT_APP_POLYGON_NODE_HTTP_URL: ${{ vars.POLYGON_NODE_HTTP_URL }}
  REACT_APP_POLYGON_NODE_WSS_URL: ${{ vars.POLYGON_NODE_WSS_URL }}
  REACT_APP_ETHEREUM_NODE_HTTP_URL: ${{ vars.ETHEREUM_NODE_HTTP_URL }}
  REACT_APP_ETHEREUM_NODE_WSS_URL: ${{ vars.ETHEREUM_NODE_WSS_URL }}
jobs:
  deploy-prod:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      # Sets node config
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "yarn"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build package
      - name: Build
        run: yarn build
        env:
          CI: false

      # Publish to CF pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: clicker-verse-bitcoin-com
          directory: build
          branch: trunk
          workingDirectory: /
          wranglerVersion: "3"
